### ISSUE TITLE
一些图不能正常显示

### ISSUE THREAD

**Issue by acgtyrant** [lilydjwg/morerssplz#1]
Inoreader, http://zhuanlan.zhihu.com/vgfans/20478677

![1452166933](https://cloud.githubusercontent.com/assets/3921062/12169852/d523f7ce-b576-11e5-9cad-d3f874dc05f2.png)

**Comment by lilydjwg** [comment]
InoReader 是通过 HTTP 还是 HTTPS 访问的？

**Comment by lilydjwg** [comment]
我用火狐，禁用跨HTTPS站 referrer（`network.http.sendSecureXSiteReferrer;false`）之后是可以在订阅页看到图片的。InoReader 里应该也一样。

如果不禁用 referrer，那么有些图片会返回 403 错误。

你也可以使用 RefControl 这类浏览器扩展来处理 referrer 带来的问题。

**Comment by acgtyrant** [comment]
不好意思现在才处理该 issue, 看来总之只和浏览器设置有关吧。

**Comment by acgtyrant** [comment]
一开始用 HTTP 访问，不过现在即使改用 HTTPS 还是一样。

**Comment by lilydjwg** [comment]
使用 HTTPS，浏览器默认还是会发送 referrer 的。你首先需要做的是确认是什么错误（服务器返回了什么结果，是 403 吗），以及请求是否带有 referrer 头。

我曾经尝试过指定这些图片不发送 referrer，但是在火狐里这个特性需要手动开启。其它浏览器大概不支持。
