### ISSUE TITLE
可不可以做一个对应的 grease monkey script?

### ISSUE THREAD

**Issue by Endle** [lilydjwg/morerssplz#13]
如果我发一个 PR， 里面是一个 grease monkey script，会编辑知乎主页，在页面上插入 “获取静态版本” “获取RSS地址” 等功能，有可能被merge吗？

**Comment by lilydjwg** [comment]
只要工作良好，欢迎呀。

你可以直接插入链接到相应的功能。还可以直接链接到 Push to Kindle 这种服务。

**Comment by Endle** [comment]
现在写了一个，有的细节需要调整一下
<https://github.com/Endle/morerssplz/blob/greasemonkey/static_endle.js>

如果直接连接到 Push to Kindle， 那title栏是不是堆的东西太多了

**Comment by lilydjwg** [comment]
还没试，不过有两个问题：

* userscript 应当以 .user.js 结尾，这样才能点击安装
* 不要用 HTTP 的图片。这个我可以给改改

**Comment by lilydjwg** [comment]
试了一下，在知乎图标旁边加了一个图标。不过有些问题：

* 这个图标并不会跟着左边的「知」一样隐藏
* 这个图标不是链接，只是响应点击事件而已。建议做个 <a> 放那里
* 跳转到静态页面时也使用 RSS 图标，不妥

至于怕堆太多东西，只考虑火狐的话，倒是可以放右键菜单里。可惜[别的浏览器都不支持](https://caniuse.com/#feat=menu)。或者在 hover 的时候放个下拉菜单过去？

**Comment by Endle** [comment]
>这个图标并不会跟着左边的「知」一样隐藏  

https://github.com/Endle/morerssplz/commit/83840491f24981d942377b32e9af263477cd3643
>这个图标不是链接，只是响应点击事件而已。建议做个 放那里  

你是说，做成一个 `<a>` 吗
>跳转到静态页面时也使用 RSS 图标，不妥  

恩，是不太合适。没找到太好的静态化图标。一个 S 字母怎么样？

>至于怕堆太多东西，只考虑火狐的话，倒是可以放右键菜单里。可惜别的浏览器都不支持。或者在 hover 的时候放个下拉菜单过去？


我不太喜欢hover，对触摸屏不太友好。。。

>userscript 应当以 .user.js 结尾，这样才能点击安装

renamed
>不要用 HTTP 的图片。这个我可以给改改

一时没找到放资源的地方。你要host到你的服务器上面吗

**Comment by lilydjwg** [comment]
> 你是说，做成一个 `<a>` 吗

对。我的 a 标签被 markdown 吃掉了……

> 恩，是不太合适。没找到太好的静态化图标。一个 S 字母怎么样？

要不 HTML 的标志？或者文档的标志？我觉得糭的「阅读模式」那个图标挺不错的。

> 我不太喜欢hover，对触摸屏不太友好。。。

触摸屏就用向下划动怎么样？

> 一时没找到放资源的地方。你要host到你的服务器上面吗

我可以扔又拍云上去。

**Comment by NormanBB** [comment]
个人觉得这个idea,挺实用,现在进度怎么样?我进去那个地址显示404。

**Comment by Endle** [comment]
我一直在跳票
先让我跳票到五月份结束期末考试吧 ：（

Zhenbo Li
From my Mobile

**Comment by NormanBB** [comment]
well. （ ’ - ’ * )

**Comment by lilydjwg** [comment]
我发现 [Redirect Link](https://addons.mozilla.org/firefox/addon/redirect-link/) 这个扩展可以做到跳转呢：打开扩展的首选项，添加一行，在「URL」部分填写 `https://rss.lilydjwg.me/static_zhihu/%p[1]?pic=google`，「Enable URL」填写 `https://zhuanlan.zhihu.com/` 即可。
