### ISSUE TITLE
知乎专栏用Inoreader订阅可以显示图片

### ISSUE THREAD

**Issue by Vstory** [lilydjwg/morerssplz#15]
然后我把所有订阅的专栏都加了
`?pic=google`
QwQ

**Comment by lilydjwg** [comment]
那个 referrer 的事么，用浏览器扩展欺骗一下就可以了。也不知道 referrer policy 现在的支持情况如何。

**Comment by Vstory** [comment]
我全部改成
`
?pic=cf
`
可以正常显示图片，我主要是在Inoreader的Web端订阅好，到移动设备看。
直接订阅不加以下
`
?pic=cf ; ?pic=google
`
我测试也可以显示图片，不过以防万一，还是加了
`
?pic=cf 
`

感谢你的回复 😀

**Comment by lilydjwg** [comment]
手机 app 是没问题的。
