### ISSUE TITLE
请问下依云是如何做图片代理的，谢谢。

### ISSUE THREAD

**Issue by BoWuGit** [lilydjwg/morerssplz#17]
也许不该开个Issue，但是好奇，可能别人也跟我有同样的问题，所以就在这问下，希望不要介意。

如文档所说：

> 如果你能访问 Google 或者 Cloudflare，可以使用它们提供的图片代理。在订阅地址后边加上 ?pic=google 或者 ?pic=cf 就可以了，例如：https://rss.lilydjwg.me/zhihuzhuanlan/dingxiangyisheng?pic=cf
https://rss.lilydjwg.me/zhihuzhuanlan/dingxiangyisheng?pic=google

**Comment by lilydjwg** [comment]
把 URL 改一下就可以了： https://github.com/lilydjwg/morerssplz/blob/master/morerss/base.py#L76-L100

https://images.weserv.nl/ 是一个专门做图片代理的网站，使用的是 Cloudflare 的网络；Google 的那个是[有人发现](https://carlo.zottmann.org/posts/2013/04/14/google-image-resizer.html)的。
