### ISSUE TITLE
知乎动态个人的没有数据

### ISSUE THREAD

**Issue by wizos** [lilydjwg/morerssplz#18]
例如：https://rss.lilydjwg.me/zhihu/fu-lan-ke-yang

**Comment by lilydjwg** [comment]
已修正，最迟几小时之后应该会生效。不过这个人发布的都是「想法」，「回答」和「文章」不多。

**Comment by wizos** [comment]
好的，谢谢。不过貌似只获取到了一个回答，是因为从 https://www.zhihu.com/people/fu-lan-ke-yang/activities 这种url获取到的数据吗？那为什么获取回答不从这个链接呢？
 https://www.zhihu.com/people/fu-lan-ke-yang/answers

**Comment by lilydjwg** [comment]
因为要同时获取回答和文章。只有一个是因为最近三天他就回答了一个吧。

**Comment by wizos** [comment]
ok，了解了，再次感谢！
