### ISSUE TITLE
知乎动态用户ID识别问题

### ISSUE THREAD

**Issue by raikyou** [lilydjwg/morerssplz#20]
知乎个人动态链接 https://rss.lilydjwg.me/zhihu/ + ID 在使用时，发现只有ID为[小写英文字母](https://rss.lilydjwg.me/zhihu/zhihuadmin)时可以正常显示RSS内容，但是当ID中有[大写英文字母](https://rss.lilydjwg.me/zhihu/BestJuly)或[连字符 -](https://rss.lilydjwg.me/zhihu/meng-hui-9-77)时则会出现错误。
请问这种状况时代码未识别还是我操作问题，谢谢!

**Comment by lilydjwg** [comment]
都没有问题。你给的两个返回结果为空的地址中，第一个回答已经是五天前，超过了我获取的时间期限，第二个本来就什么内容都没有嘛。

**Comment by raikyou** [comment]
好的，我以为是抓取页面上的所有内容，刚才看到了 上一个 closed issue ，是抓取订阅后的更新内容，我理解错了。
总之，谢谢了！
