### ISSUE TITLE
我有个疑问，请问订阅的内容已经抓取到rss阅读器里了，然后这个内容被删除了，阅读器里的还在吗？

### ISSUE THREAD

**Issue by jin6220** [lilydjwg/morerssplz#22]
另外，还找到做rss工具但是不会用
作者给出的的@vczh的订阅地址：
http://www.feeddiy.com/rss/FBV3ea
轮子哥的地址放进去rss阅读器之后可以无限下拉阅读，不受限制。
链接：https://www.zhihu.com/question/27621722/answer/147637484

**Comment by lilydjwg** [comment]
我见过的在线阅读器的话，删除的内容都是在的，修改过的就只有修改之后的了。

那些通用 RSS 生成器都需要一些 HTML 的知识的。你可以去 w3school 学的。

**Comment by jin6220** [comment]
@lilydjwg   会一点html基础 但是他这个不太会用。3q 我再研究下。

**Comment by lilydjwg** [comment]
它这个是图形界面的，对新手友好一些，不过还是得了解基本的页面结构。然后一步一步选下去就可以了。不知道支不支持动态生成的页面。

**Comment by vczh** [comment]
中枪
