### ISSUE TITLE
关于知乎专栏文章静态化

### ISSUE THREAD

**Issue by NormanBB** [lilydjwg/morerssplz#23]
似乎现在服务已不可用。
我将示例里面 https://rss.lilydjwg.me/static_zhihu/27746434
的这个网站粘贴到push to kindle 里面，网站不能获取网页内容。
难道挂了？

**Comment by lilydjwg** [comment]
大概是知乎改了页面，需要重新适配。

**Comment by lilydjwg** [comment]
修好了。
