### ISSUE TITLE
为什么个人动态抓取一周前的？

### ISSUE THREAD

**Issue by Azureki** [lilydjwg/morerssplz#25]
为什么[这里](https://github.com/Azureki/morerssplz/blob/ab2e931ccf9f6dea4a18fc24a500b825d41f1ab3/morerss/zhihu_stream.py#L31)要把时间往前推一周？

唔也不能算是issue吧，就是好奇。  
不过奇怪的是你搭的服务竟然是没问题的。动态就是抓取到今天，而不是一周前……（沉思）

**Comment by lilydjwg** [comment]
因为 after 不是 before 呀。这个是只抓最近一周的内容。细节不记得了，大概是默认抓的时间段太短了吧。

**Comment by Azureki** [comment]
原来是这样，我明白了。谢谢依云。（我还以为是本地改了，但是没有push。）

这样看来，我直接运行时抓取到一周前的动态，去掉`-86400 * 7`就是今日动态，还是我的问题，我再看看……

**Comment by lilydjwg** [comment]
最近的更新之后，除了代理模块，我本地现在已经没有修改没 push 了。

**Comment by lilydjwg** [comment]
咦不对，你引用的代码是旧版本的。在 5a86baaa 里已经去掉那个参数了（因为不再有效，而不是语义有问题）。

**Comment by Azureki** [comment]
0.0  
确实……这下没疑问了。  
此issue终结。
