### ISSUE TITLE
知乎专栏订阅时缺少

### ISSUE THREAD

**Issue by Tatsumi00** [lilydjwg/morerssplz#28]
比如一个专栏有几十篇，往往只能更新到20篇，猜测是因为知乎的浏览器下拉内容限制，在rss订阅时，只收录了初始的文章

**Comment by lilydjwg** [comment]
RSS 是这样的啊，只有最新的内容。你是说有的专栏发布文章的速度很快，造成两次获取之间有遗漏吗？

**Comment by Tatsumi00** [comment]
看到了之前的问题，已经知道怎么解决了，谢谢您的回复了
