### ISSUE TITLE
知乎专栏订阅更新不及时

### ISSUE THREAD

**Issue by qzshadow** [lilydjwg/morerssplz#29]
您好，很感谢你的工作！

有个问题，我订阅了 `arXiv每日论文速递` 这样一个专栏，但是rss跟新好像很不及时，比如今天18日，rss最新的只有15日的内容，但是我看了知乎的专栏已经跟新到18日了，请问这个是为什么？

谢谢！

**Comment by lilydjwg** [comment]
那个是一小时前的内容呀。由于缓存你可能得等最多四小时（如果我没记错的话）才会看到更新。
