### ISSUE TITLE
生成的 RSS 内容中如有<>之类的字符，会二次转义

### ISSUE THREAD

**Issue by vayn** [lilydjwg/morerssplz#3]
案发地址：https://rss.lilydjwg.me/zhihuzhuanlan/rust-lang

比如`<T>`正常转义为`&gt;T&lt;`，但实际被转义成 `&amp;lt;T&amp;gt;` 导致 RSS 在 Feedly 中被截断（即使不截断也会显示成一团乱麻……
应该是 PyRSS2Gen 的锅我猜。

**Comment by lilydjwg** [comment]
这没问题呀，火狐和 InoReader 都能正常显示。最里层转义是 HTML 的，然后把 HTML 装在 XML 里又得转义一次，就成那样了。

去找找 Feedly？

**Comment by vayn** [comment]
如此说来就是Feedly的问题了，我才懒得找Feedly，一会儿搬家好了~~



 
发件人： 依云
发送时间： 2016-12-05 11:46
收件人： lilydjwg/morerssplz
抄送： Vincent Tsai; Author
主题： Re: [lilydjwg/morerssplz] 生成的 RSS 内容中如有<>之类的字符，会二次转义 (#3)
这没问题呀，火狐和 InoReader 都能正常显示。最里层转义是 HTML 的，然后把 HTML 装在 XML 里又得转义一次，就成那样了。
去找找 Feedly？

**Comment by vayn** [comment]
试着联系了一下 Feedly，没想到他家的 support 点进去就是个 Black Friday 促销广告，彻底转移到 inoreader 啦。

**Comment by lilydjwg** [comment]
好差的 support……

**Comment by lilydjwg** [comment]
@Vayn 对了，来加我的 InoReader 好友～我的名字是「依云-lilydjwg」。

**Comment by vayn** [comment]
已经订阅啦
