### ISSUE TITLE
全文尚不可用

### ISSUE THREAD

**Issue by Huang-CL** [lilydjwg/morerssplz#30]
我用您的工具生成知乎专栏 一颗青木的rss，地址是https://zhuanlan.zhihu.com/c_1172376292363636736
按照您的格式，我用的rss地址是https://rss.lilydjwg.me/zhihuzhuanlan/c_1172376292363636736?pic=google
除了第一次推送正常以外，之后推送的文章总是只有个开头，结束的地方括号写着“全文尚不可用”。
请问有什么办法解决么？谢谢

**Comment by lilydjwg** [comment]
现在全文已经出来了。如果你的阅读器不支持更新文章内容那就抱歉了，没什么好的办法。

这么处理的原因是，获取全文需要额外的到知乎的请求。这些请求可能需要较长时间，可能暂时无法成功，所以是在获取之后加入队列来处理的。另外生成的 RSS 在 CDN 服务器上有缓存，所以一般是第二次回源的时候才能看到更新。同一地域的话缓存有效期可能长达四小时之久。

**Comment by Huang-CL** [comment]
我是使用kindle4rss自动推送到kindle上。我去看看有没有什么办法能更新内容。谢谢

**Comment by lilydjwg** [comment]
我在考虑，要不要做一个仅输出已获得全文的文章（没有全文的文章被忽略），这样对于 Kindle 推送来说就能总是取得全文了。不过这样有个副作用是，旧的文章可能在新的文章之后才出现（比如一次访问有「A、C、D」三篇文章，下一次访问有「A、B、C、D、E」，B 和 E 是后来才拿到全文的）。这可能也会导致问题。

**Comment by Huang-CL** [comment]
就我个人的使用来说，只要有全文就好，顺序并不重要。

**Comment by lilydjwg** [comment]
加了个 `fullonly=true` 参数，你加后边就好，比如： https://rss.lilydjwg.me/zhihuzhuanlan/c_1172376292363636736?pic=google&fullonly=true
