### ISSUE TITLE
Subscribing Zhihu topics

### ISSUE THREAD

**Issue by SiqingYu** [lilydjwg/morerssplz#31]
Not duplicated with https://github.com/lilydjwg/morerssplz/issues/7

I'm currently working on this issue. I opened it for commenting and discussing.

There are two sorting methods of Zhihu：

1. Sort by newest：
<img width="555" alt="newest" src="https://user-images.githubusercontent.com/22290018/75209746-07865880-57ba-11ea-88fc-2fc6b6b6187d.png">

2. Sort by popularity：
<img width="536" alt="hot" src="https://user-images.githubusercontent.com/22290018/75209749-09e8b280-57ba-11ea-8897-4e639e59e0a6.png">

**Comment by lilydjwg** [comment]
You can support both via a query argument, though I don't see why people may want to subscribe to hot ones.

**Comment by sschyu** [comment]
@lilydjwg Sorting by popularity is the default option of Zhihu topics. While the "newest" option lists all questions and answers under a topic, the "hot" option only catalogs some if them. IME, the "newest" feeds are too noisy, as in [RSSHub's Zhihu topics feeds](https://docs.rsshub.app/social-media.html#zhi-hu), which might be consumed only by marketing or news monitoring people. The "hot" option makes more sense though it also has lots of updates.

**Comment by lilydjwg** [comment]
Yes, that's why I suggest support both. It doesn't seem a lot of work. BTW if it updates very frequently you may want to lower the cache time.
