### ISSUE TITLE
知乎动态已经失效

### ISSUE THREAD

**Issue by lilydjwg** [lilydjwg/morerssplz#44]

**Comment by Angynond** [comment]
请问预计多久可以恢复

**Comment by lilydjwg** [comment]
没有预计时间。如果有人能发出可用的 pull request 的话很快就能恢复。如果等我来修的话，大概需要等很多天。

**Comment by sschyu** [comment]
知乎用户动态的功能，我也在用，也许我可以帮下忙，今晚我看下。

**Comment by SiqingYu** [comment]
https://github.com/lilydjwg/morerssplz/pull/45
