### ISSUE TITLE
为什么不支持用户的关注页面的RSS呢？我觉得这个才是最重要的需求

### ISSUE THREAD

**Issue by chaixuqing** [lilydjwg/morerssplz#46]

**Comment by lilydjwg** [comment]
因为没有人实现？

**Comment by lilydjwg** [comment]
因为没有人实现？

**Comment by lilydjwg** [comment]
另外我没理解「用户的关注页面」是指的什么？哪个网站？知乎？有这么个页面吗？

**Comment by sschyu** [comment]
@chaixuqing 指的是这个页面：

<img width="784" alt="Screen Shot 2022-01-21 at 5 32 04 PM" src="https://user-images.githubusercontent.com/22290018/150502808-c1c77340-8c2b-4f05-ab14-9ede543d812e.png">

这是一个时间线，内容是关注用户的动态，包括回答、赞同、文章。

但是我认为 morerssplz 不宜实现该功能，理由如下：

1. 既然关注这个页面，为何不上知乎网站或者知乎app直接看？
2. 用户自己的时间线，需要登录才能查看，不适合用该项目的公共静态网页 https://rss.lilydjwg.me/ 查看。
