### ISSUE TITLE
有没有办法抓取整个问题成一个RSS

### ISSUE THREAD

**Issue by richmondming** [lilydjwg/morerssplz#50]
有没有办法抓取整个问题成一个RSS

**Comment by lilydjwg** [comment]
你是指 /zhihu_question/ 这个吗？

**Comment by richmondming** [comment]
是的，类似某个question截止到今日的所有回答。

在 2021-09-18 10:51:15，"依云" ***@***.***> 写道：


你是指 /zhihu_question/ 这个吗？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lilydjwg** [comment]
那不是已经有了吗？

**Comment by richmondming** [comment]
是我没有仔细看么？明天我再研究一下，谢谢回复，不懂再来讨教。

在 2021-09-25 00:14:27，"依云" ***@***.***> 写道：


那不是已经有了吗？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
