### ISSUE TITLE
知乎问题解析不了

### ISSUE THREAD

**Issue by KanswerG** [lilydjwg/morerssplz#52]
只有例子的那一个能解析，换一个问题ID就会失败

**Comment by lilydjwg** [comment]
@Ynjxsjmh 你知道现在要怎么调用问题 API 吗？

**Comment by Ynjxsjmh** [comment]
https://www.zhihu.com/api/questions/50408698 这个 api 404 了（没测试其它的 api 是否还在正常工作），但是 get_json() 方法里面就是用 `https://www.zhihu.com/api/` 来组装 api 的

https://github.com/lilydjwg/morerssplz/blob/209db7f23361234592ecf4d5e8cb0218e35291af/morerss/zhihu_stream.py#L98-L100

https://api.zhihu.com/questions/50408698 这个 api 还在正常工作

**Comment by Ynjxsjmh** [comment]
https://www.zhihu.com/api/v4/questions/ 这个 api 在我这有时候能返回值，有时候却说请求参数异常。目前 https://api.zhihu.com/questions/ 这个 api 倒是可以正常返回，不过 `get_json()` 函数里写死了 api 构造方法

https://github.com/lilydjwg/morerssplz/blob/209db7f23361234592ecf4d5e8cb0218e35291af/morerss/zhihu_stream.py#L98-L100

**Comment by lilydjwg** [comment]
好，那我改一下应该就好了。
