### ISSUE TITLE
代码中包含认证信息的明文，会不会有安全隐患

### ISSUE THREAD

**Issue by sthannahl** [lilydjwg/morerssplz#54]
![image](https://user-images.githubusercontent.com/69861631/169769211-b0bab6a0-27ac-4bcd-8c44-16a8652f796d.png)

**Comment by lilydjwg** [comment]
这个是匿名访问知乎网页所得到的 token。

**Comment by sthannahl** [comment]
> 这个是匿名访问知乎网页所得到的 token。

哦豁 那知乎还是留了很多口子的 哈哈

**Comment by stackoverflow1024** [comment]
> 这个是匿名访问知乎网页所得到的 token。

老哥 似乎最近知乎很多帖子返回的都是乱码
麻烦有空排查下😯
