### ISSUE TITLE
关于知乎输出摘要的疑问

### ISSUE THREAD

**Issue by stackoverflow1024** [lilydjwg/morerssplz#55]
RSSHUB知乎问题的feed已经挂了好久了
感谢大神提供知乎问题的RSS

以网站教程中的例子如 https://www.zhihu.com/question/50408698
订阅地址https://rss.lilydjwg.me/zhihu_question/50408698
对于输出摘要，格式为：https://rss.lilydjwg.me/zhihu_question/50408698?digest=true
加上之后和原先的对比了下在RSS Reader下似乎没有什么区别 是食用的方式不对吗😄

另外如果加上pic参数的话 中间应该怎么连接 用&这样吗
https://rss.lilydjwg.me/zhihu_question/50408698?pic=google&digest=true

**Comment by lilydjwg** [comment]
知乎问题不支持摘要。

是用 & 连接。

**Comment by stackoverflow1024** [comment]
感谢大神回复

另外还有个问题，我看到知乎问题的回答还支持google／cf图床
还以上面的例子为例 https://rss.lilydjwg.me/zhihu_question/50408698?pic=google
考虑到手机等平台上有时候流量会比较吃紧 后面可以考虑如果回答里面带图片的话可以在标题上追加PIC等tag吗
这样外出使用流量的情况下可以直接看标题判断回答中是否带图 不需要担心流量问题
而且RSS Reader上也不用维护两个feed 一个带pic参数 一个不带pic参数😄

**Comment by lilydjwg** [comment]
都是带图的啊，用图床是为了避免部分客户端里图片显示不出来的问题。

要节省流量，你可以让你的阅读器不要加载图片。

**Comment by stackoverflow1024** [comment]
对的 我的意思如果带pic参数 因为很大一部分回答中都是没有图片的 这样即使使用流量情况下也可以放心打开
单纯为了省流量确实可以使用不带pic参数的 但是室内Wi-Fi情况下又看不到图了……
在标题上添加pic这样的tag可以快速帮助用户了解文章是否带图
不然每个问题都得维护两套feed😅

**Comment by lilydjwg** [comment]
我的意思是，带不带 pic 参数，都是有图片的。

省流量这件事应该是你的客户端来做，比如流量计费网络就默认不加载图片。

**Comment by stackoverflow1024** [comment]
明白了 感谢大神👍

**Comment by stackoverflow1024** [comment]
问题解决

**Comment by lilydjwg** [comment]
另外所有图片来源都是有可能加载不出来的：

* 默认直接从知乎获取图片，如果你的客户端带了 referrer 并且它不是知乎的话，就会失败
* Google 如果不喜欢你的网络的话就会失败
* Cloudflare 如果觉得你不是人类、需要过人类验证的话，由于图片不是网页，也会失败

**Comment by stackoverflow1024** [comment]
感谢大神解释👍
