### ISSUE TITLE
知乎专栏RSS只能抓到第一页

### ISSUE THREAD

**Issue by the0demiurge** [lilydjwg/morerssplz#6]
如题，我的rss阅读器设置为最多抓取几年前的rss，然而只抓到20篇
![image](https://cloud.githubusercontent.com/assets/11363529/21294587/20fe6796-c57b-11e6-920e-16d237e494a1.png)
![image](https://cloud.githubusercontent.com/assets/11363529/21294591/420c3c60-c57b-11e6-81b2-c2e4ccf642a5.png)

**Comment by vayn** [comment]
这不是 bug 哟，RSS 提供的文章摘要数量通常是有限的。像 WordPress 这样的程序只提供近 10  篇文章的 RSS 摘要。

之所以有的阅读器能看到历史文章，是因为这样的阅读器会对之前 RSS 源之前输出的摘要进行存档。这是阅读器的功能，而非 RSS 的功能。

当然你可以 fork morerssplz，通过修改摘要输出数量，达到你想要的效果，就是这一行：

https://github.com/lilydjwg/morerssplz/blob/master/morerss/zhihu.py#L36

**Comment by lilydjwg** [comment]
嗯，没听说过 RSS 有指定取历史数据的功能。你的阅读器界面上的设置，应该是指的保留多么久的数据。

如果你想抓老的数据，自己改一下代码吧。

**Comment by the0demiurge** [comment]
@Vayn 谢谢啦！找个时间折腾一下
