### ISSUE TITLE
订阅知乎话题精华

### ISSUE THREAD

**Issue by reeselaye** [lilydjwg/morerssplz#7]
@lilydjwg 您好，不知是否有考虑过订阅知乎特定话题的精华回答呢？
示例：https://www.zhihu.com/topic/19567930/top-answers
示例截图：

![qq 20170221173131](https://cloud.githubusercontent.com/assets/17255126/23158876/a54fa024-f85b-11e6-9c5b-6bcf0d3d0365.png)

**Comment by lilydjwg** [comment]
可以啊。不过我没有这个需求，暂时还没有时间做这个。要不你来个 pull request？

**Comment by reeselaye** [comment]
抱歉，我目前是研究狗一个，也没有做这个的经验，但是一旦有时间，我想试试看！

**Comment by sschyu** [comment]
知乎话题的精华是按照点赞数排序的，那么旧回答只要保持着大量点赞数，新的低赞的回答不会出现在该话题的精华页面，也就不会有新的内容出现，因此订阅话题精华几乎没有意义。

**Comment by lilydjwg** [comment]
鉴于本问题长期无活动并且已有话题订阅功能，此问题关闭。
