### ISSUE TITLE
订阅的知乎专栏无法显示图片

### ISSUE THREAD

**Issue by AaronL-ee** [lilydjwg/morerssplz#8]
无法显示图片
![1](https://cloud.githubusercontent.com/assets/10268142/23296107/9208c752-faae-11e6-9be9-10ed62b2cf53.PNG)
![2](https://cloud.githubusercontent.com/assets/10268142/23296112/95272500-faae-11e6-9856-1bd4c8e2c0f6.PNG)
![3](https://cloud.githubusercontent.com/assets/10268142/23296113/9701f5f8-faae-11e6-88a6-828ff3742a0a.PNG)

**Comment by lilydjwg** [comment]
如果你发现访问的文章中的图片没有显示，那是因为知乎做了限制。如果你可以使用如下方案：

* 使用 RefControl 扩展来禁止火狐向知乎图片发送 referrer。
* 打开 about:config 页面，搜索 network.http.sendSecureXSiteReferrer 并双击使之成为 false。这样火狐不会向不同域名的 HTTPS 网站发送 referrer。
* 如果你能访问 Google 或者 CloudFlare，可以使用它们提供的图片代理。在 URL 后边加上 `?pic=google` 或者 `?pic=cf` 就可以了。
