### ISSUE TITLE
mac上使用是有ssl证书验证问题

### ISSUE THREAD

**Issue by luoshuhui** [lilydjwg/morerssplz#9]
错误日志的一部分是    

[log.txt](https://github.com/lilydjwg/morerssplz/files/1030978/log.txt)

**Comment by lilydjwg** [comment]
你 curl https://zhuanlan.zhihu.com/ 正常吗？

**Comment by luoshuhui** [comment]
正常的。

**Comment by luoshuhui** [comment]
zhihu.py:58
    res = yield httpclient.fetch(url, raise_error=False,validate_cert=False)
就好了。

**Comment by lilydjwg** [comment]
不验证证书这习惯可不好。

你试试这段代码呢？

```py
#!/usr/bin/env python3

import socket, ssl

def test():
  sock = socket.socket()
  sock.connect(('118.178.213.186', 443))
  ctx = ssl.create_default_context()
  sock = ctx.wrap_socket(sock, server_hostname='zhuanlan.zhihu.com')
  sock.close()

if __name__ == '__main__':
  test()
```

**Comment by luoshuhui** [comment]
不行，问题是一样的。

**Comment by lilydjwg** [comment]
```py
import ssl
print(ssl.get_default_verify_paths())
```

结果如何？

**Comment by luoshuhui** [comment]
没有异常
DefaultVerifyPaths(cafile='/usr/local/etc/openssl/cert.pem', capath='/usr/local/etc/openssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/usr/local/etc/openssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/usr/local/etc/openssl/certs')

**Comment by lilydjwg** [comment]
`ssl.HAS_SNI` 呢？

**Comment by luoshuhui** [comment]
return True.

**Comment by lilydjwg** [comment]
Wireshark / tcpdump 抓个包吧。
